package com.example.data.playlist

import com.example.data.model.Channel
import java.io.BufferedReader
import java.io.InputStream
import java.io.InputStreamReader
import java.net.URI
import java.util.regex.Pattern

data class M3uParseResult(
    val channels: List<Channel>,
    val totalEntries: Int,
    val skippedEntries: Int
)

object M3uParser {
    // Dedicated patterns for resilient matching
    private val TVG_ID_PATTERN = Pattern.compile("tvg-id=[\"']?([^\"',\\s]+)[\"']?", Pattern.CASE_INSENSITIVE)
    private val TVG_NAME_PATTERN = Pattern.compile("tvg-name=[\"']?([^\"',]+)[\"']?", Pattern.CASE_INSENSITIVE)
    private val TVG_LOGO_PATTERN = Pattern.compile("tvg-logo=[\"']?([^\"',\\s]+)[\"']?", Pattern.CASE_INSENSITIVE)
    private val TVG_CHNO_PATTERN = Pattern.compile("tvg-chno=[\"']?(\\d+)[\"']?", Pattern.CASE_INSENSITIVE)
    private val GROUP_TITLE_PATTERN = Pattern.compile("group-title=[\"']?([^\"',]+)[\"']?", Pattern.CASE_INSENSITIVE)
    private val TVG_LANG_PATTERN = Pattern.compile("tvg-language=[\"']?([^\"',\\s]+)[\"']?", Pattern.CASE_INSENSITIVE)
    private val TVG_COUNTRY_PATTERN = Pattern.compile("tvg-country=[\"']?([^\"',\\s]+)[\"']?", Pattern.CASE_INSENSITIVE)

    /**
     * Parses an M3U/M3U8 input stream line-by-line with zero crash risk.
     * Extracts clean stream URLs, pipe headers (|User-Agent=...), channel numbers, and metadata.
     */
    fun parse(inputStream: InputStream, providerId: String): M3uParseResult {
        val channels = ArrayList<Channel>()
        val reader = BufferedReader(InputStreamReader(inputStream, Charsets.UTF_8), 16384)
        var totalEntriesFound = 0
        var skippedCount = 0

        var currentTvgId = ""
        var currentTvgName = ""
        var currentLogoUrl: String? = null
        var currentGroup = "General"
        var currentChNo: Int? = null
        var currentLang = ""
        var currentCountry = ""
        var currentDisplayName = ""
        var currentExtVlcHeaders = mutableMapOf<String, String>()
        var autoGeneratedNumber = 1

        try {
            var line: String? = reader.readLine()
            while (line != null) {
                val trimmed = line.trim()
                if (trimmed.isEmpty()) {
                    line = reader.readLine()
                    continue
                }

                if (trimmed.startsWith("#EXTINF:", ignoreCase = true)) {
                    totalEntriesFound++

                    // Extract tvg-id
                    val idMatcher = TVG_ID_PATTERN.matcher(trimmed)
                    currentTvgId = if (idMatcher.find()) idMatcher.group(1)?.trim().orEmpty() else ""

                    // Extract tvg-name
                    val nameMatcher = TVG_NAME_PATTERN.matcher(trimmed)
                    currentTvgName = if (nameMatcher.find()) nameMatcher.group(1)?.trim().orEmpty() else ""

                    // Extract tvg-logo
                    val logoMatcher = TVG_LOGO_PATTERN.matcher(trimmed)
                    currentLogoUrl = if (logoMatcher.find()) {
                        val logo = logoMatcher.group(1)?.trim()
                        if (!logo.isNullOrBlank() && (logo.startsWith("http://", ignoreCase = true) || logo.startsWith("https://", ignoreCase = true))) {
                            logo
                        } else null
                    } else null

                    // Extract tvg-chno
                    val chnoMatcher = TVG_CHNO_PATTERN.matcher(trimmed)
                    currentChNo = if (chnoMatcher.find()) {
                        chnoMatcher.group(1)?.toIntOrNull()
                    } else null

                    // Extract group-title
                    val groupMatcher = GROUP_TITLE_PATTERN.matcher(trimmed)
                    currentGroup = if (groupMatcher.find()) {
                        val g = groupMatcher.group(1)?.trim().orEmpty()
                        if (g.isNotEmpty()) g else "General"
                    } else "General"

                    // Extract tvg-language & country
                    val langMatcher = TVG_LANG_PATTERN.matcher(trimmed)
                    currentLang = if (langMatcher.find()) langMatcher.group(1)?.trim().orEmpty() else ""

                    val countryMatcher = TVG_COUNTRY_PATTERN.matcher(trimmed)
                    currentCountry = if (countryMatcher.find()) countryMatcher.group(1)?.trim().orEmpty() else ""

                    // Extract Channel title following the last comma
                    val commaIndex = trimmed.lastIndexOf(',')
                    currentDisplayName = if (commaIndex != -1 && commaIndex < trimmed.length - 1) {
                        trimmed.substring(commaIndex + 1).trim()
                    } else {
                        currentTvgName.ifEmpty { "Channel $autoGeneratedNumber" }
                    }

                } else if (trimmed.startsWith("#EXTGRP:", ignoreCase = true)) {
                    val grp = trimmed.substringAfter(":").trim()
                    if (grp.isNotEmpty()) {
                        currentGroup = grp
                    }
                } else if (trimmed.startsWith("#EXTVLCOPT:", ignoreCase = true)) {
                    val option = trimmed.substringAfter(":").trim()
                    val eqIndex = option.indexOf('=')
                    if (eqIndex != -1) {
                        val optKey = option.substring(0, eqIndex).trim().lowercase()
                        val optVal = option.substring(eqIndex + 1).trim()
                        if (optKey.contains("user-agent")) {
                            currentExtVlcHeaders["User-Agent"] = optVal
                        } else if (optKey.contains("referrer") || optKey.contains("referer")) {
                            currentExtVlcHeaders["Referer"] = optVal
                        }
                    }
                } else if (!trimmed.startsWith("#")) {
                    // This is expected to be the stream URL
                    val (cleanUrl, extractedHeaders) = sanitizeAndExtractUrl(trimmed)
                    if (isValidStreamUrl(cleanUrl)) {
                        val mergedHeaders = HashMap(currentExtVlcHeaders)
                        mergedHeaders.putAll(extractedHeaders)

                        val assignedNumber = currentChNo ?: autoGeneratedNumber
                        val finalName = currentDisplayName.ifEmpty {
                            currentTvgName.ifEmpty { "Channel $assignedNumber" }
                        }

                        val channelId = "${providerId}_${channels.size + 1}_${cleanUrl.hashCode()}"
                        val channel = Channel(
                            id = channelId,
                            providerId = providerId,
                            channelNumber = assignedNumber,
                            name = finalName,
                            streamUrl = cleanUrl,
                            logoUrl = currentLogoUrl,
                            group = currentGroup,
                            tvgId = currentTvgId,
                            tvgName = currentTvgName,
                            headers = mergedHeaders,
                            language = currentLang,
                            country = currentCountry,
                            isPlayable = true
                        )
                        channels.add(channel)
                        autoGeneratedNumber++
                    } else {
                        skippedCount++
                    }

                    // Reset per-channel metadata holders
                    currentTvgId = ""
                    currentTvgName = ""
                    currentLogoUrl = null
                    currentGroup = "General"
                    currentChNo = null
                    currentLang = ""
                    currentCountry = ""
                    currentDisplayName = ""
                    currentExtVlcHeaders.clear()
                }

                line = reader.readLine()
            }
        } catch (_: Exception) {
            // Safety: Return whatever was parsed safely rather than crashing
        } finally {
            try {
                reader.close()
            } catch (_: Exception) {}
        }

        return M3uParseResult(
            channels = channels,
            totalEntries = if (totalEntriesFound > 0) totalEntriesFound else channels.size,
            skippedEntries = skippedCount
        )
    }

    /**
     * Extracts clean URL and pipe-separated HTTP headers.
     * e.g. "http://example.com/live.m3u8|User-Agent=VLC&Referer=http://foo.com"
     */
    fun sanitizeAndExtractUrl(rawUrl: String): Pair<String, Map<String, String>> {
        val cleanRaw = rawUrl.trim().replace("\r", "")
        val pipeIdx = cleanRaw.indexOf('|')
        if (pipeIdx == -1) {
            return Pair(cleanRaw, emptyMap())
        }

        val baseStreamUrl = cleanRaw.substring(0, pipeIdx).trim()
        val headersString = cleanRaw.substring(pipeIdx + 1).trim()
        val headers = mutableMapOf<String, String>()

        val headerPairs = headersString.split('&', ';')
        for (pair in headerPairs) {
            val eq = pair.indexOf('=')
            if (eq != -1) {
                val key = pair.substring(0, eq).trim()
                val value = pair.substring(eq + 1).trim()
                if (key.isNotEmpty() && value.isNotEmpty()) {
                    headers[key] = value
                }
            }
        }

        return Pair(baseStreamUrl, headers)
    }

    /**
     * Checks if a stream URL is structurally valid for network or local playback.
     */
    fun isValidStreamUrl(url: String): Boolean {
        if (url.isBlank()) return false
        val lower = url.lowercase()
        val hasValidScheme = lower.startsWith("http://") ||
            lower.startsWith("https://") ||
            lower.startsWith("rtmp://") ||
            lower.startsWith("rtsp://") ||
            lower.startsWith("file://") ||
            lower.startsWith("content://")

        if (!hasValidScheme) return false

        return try {
            val uri = URI.create(url)
            uri.scheme != null && (uri.host != null || lower.startsWith("content://") || lower.startsWith("file://"))
        } catch (_: Exception) {
            try {
                val encoded = url.replace(" ", "%20")
                val uri = URI.create(encoded)
                uri.scheme != null
            } catch (_: Exception) {
                false
            }
        }
    }
}
